package me.dio.designpatterns;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;

/**
 * Spring Boot Project generated by Spring Initializr
 * The following dependencies were added:
 * - Spring Web
 * - Spring Boot Dev Tools
 * - Spring Data JPA
 * - OpenFeign
 * - H2 Database
 * - Lombok
 *
 * @author gpmrks
 *
 */

@EnableFeignClients
@SpringBootApplication
public class DesignPatternsApplication {

	public static void main(String[] args) {
		SpringApplication.run(DesignPatternsApplication.class, args);
	}

}
